apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
  labels:
    app: devops-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: devops-demo